In [ ]:
import pandas as pd
pharma_data = pd.read_csv('https://raw.githubusercontent.com/dphi-official/Datasets/master/pharma_data/Training_set_begs.csv')

In [ ]:
test_data = pd.read_csv('https://raw.githubusercontent.com/dphi-official/Datasets/master/pharma_data/Testing_set_begs.csv')

In [ ]:
pharma_data.shape,test_data.shape

((23097, 18), (9303, 17))

In [ ]:
pharma_data.isnull().sum(),test_data.isnull().sum()

(ID_Patient_Care_Situation       0
 Diagnosed_Condition             0
 Patient_ID                      0
 Treated_with_drugs             13
 Patient_Age                     0
 Patient_Body_Mass_Index         0
 Patient_Smoker                  0
 Patient_Rural_Urban             0
 Patient_mental_condition        0
 A                            1235
 B                            1235
 C                            1235
 D                            1235
 E                            1235
 F                            1235
 Z                            1235
 Number_of_prev_cond          1235
 Survived_1_year                 0
 dtype: int64, ID_Patient_Care_Situation    0
 Diagnosed_Condition          0
 Patient_ID                   0
 Treated_with_drugs           0
 Patient_Age                  0
 Patient_Body_Mass_Index      0
 Patient_Smoker               0
 Patient_Rural_Urban          0
 Patient_mental_condition     0
 A                            0
 B                            0
 C                            0
 D                            0
 E                            0
 F                            0
 Z                            0
 Number_of_prev_cond          0
 dtype: int64)

In [ ]:
pharma_data.head()

   ID_Patient_Care_Situation  ...  Survived_1_year
0                      22374  ...                0
1                      18164  ...                1
2                       6283  ...                0
3                       5339  ...                1
4                      33012  ...                1

[5 rows x 18 columns]

In [ ]:
df=pharma_data

In [ ]:
df.shape

(23097, 18)

In [ ]:
df.dropna(subset=['Treated_with_drugs'],inplace=True)

In [ ]:
df

       ID_Patient_Care_Situation  ...  Survived_1_year
0                          22374  ...                0
1                          18164  ...                1
2                           6283  ...                0
3                           5339  ...                1
5                          10808  ...                0
...                          ...  ...              ...
23092                      15613  ...                0
23093                      15503  ...                1
23094                       2167  ...                0
23095                      31646  ...                1
23096                       3947  ...                0

[23084 rows x 18 columns]

In [ ]:
df.isnull().sum()

ID_Patient_Care_Situation       0
Diagnosed_Condition             0
Patient_ID                      0
Treated_with_drugs              0
Patient_Age                     0
Patient_Body_Mass_Index         0
Patient_Smoker                  0
Patient_Rural_Urban             0
Patient_mental_condition        0
A                            1235
B                            1235
C                            1235
D                            1235
E                            1235
F                            1235
Z                            1235
Number_of_prev_cond          1235
Survived_1_year                 0
dtype: int64

In [ ]:
d=df[['A','B','C','D','E','F','Z','Number_of_prev_cond','Survived_1_year']]

In [ ]:
d.corr()

                            A         B  ...  Number_of_prev_cond  Survived_1_year
A                    1.000000 -0.064556  ...             0.169220        -0.048654
B                   -0.064556  1.000000  ...             0.392672        -0.049633
C                   -0.090918 -0.021290  ...             0.445228        -0.033144
D                   -0.076801 -0.002122  ...             0.320661        -0.105593
E                   -0.164966 -0.017999  ...             0.541631         0.021906
F                   -0.054944 -0.016070  ...             0.257548         0.004184
Z                         NaN       NaN  ...                  NaN              NaN
Number_of_prev_cond  0.169220  0.392672  ...             1.000000        -0.080747
Survived_1_year     -0.048654 -0.049633  ...            -0.080747         1.000000

[9 rows x 9 columns]

In [ ]:
df.dropna(subset=['A','B','C','D','E','F','Z','Number_of_prev_cond'],inplace=True)

In [ ]:
df.isnull().sum()

ID_Patient_Care_Situation    0
Diagnosed_Condition          0
Patient_ID                   0
Treated_with_drugs           0
Patient_Age                  0
Patient_Body_Mass_Index      0
Patient_Smoker               0
Patient_Rural_Urban          0
Patient_mental_condition     0
A                            0
B                            0
C                            0
D                            0
E                            0
F                            0
Z                            0
Number_of_prev_cond          0
Survived_1_year              0
dtype: int64

Feature Engineering
cat

In [ ]:
df

       ID_Patient_Care_Situation  ...  Survived_1_year
0                          22374  ...                0
1                          18164  ...                1
2                           6283  ...                0
3                           5339  ...                1
5                          10808  ...                0
...                          ...  ...              ...
23092                      15613  ...                0
23093                      15503  ...                1
23094                       2167  ...                0
23095                      31646  ...                1
23096                       3947  ...                0

[21849 rows x 18 columns]

In [ ]:
df.Treated_with_drugs.nunique()

32

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
#df['Treated_with_drugs_Enco']=LabelEncoder().fit_transform(df.Treated_with_drugs)
#test_data['Treated_with_drugs_Enco']=LabelEncoder().fit_transform(test_data.Treated_with_drugs)

In [ ]:
df

       ID_Patient_Care_Situation  ...  Patient_mental_condition_Enco
0                          22374  ...                              0
1                          18164  ...                              0
2                           6283  ...                              0
3                           5339  ...                              0
5                          10808  ...                              0
...                          ...  ...                            ...
23092                      15613  ...                              0
23093                      15503  ...                              0
23094                       2167  ...                              0
23095                      31646  ...                              0
23096                       3947  ...                              0

[21849 rows x 31 columns]

In [ ]:
test_data.Treated_with_drugs.unique()

array(['DX3 ', 'DX6', 'DX4 DX5 ', 'DX1 DX2 ', 'DX1 DX2 DX4 ', 'DX2 ',
       'DX5 ', 'DX3 DX4 DX5 ', 'DX1 DX3 ', 'DX1 ', 'DX2 DX5 ', 'DX1 DX4 ',
       'DX2 DX3 ', 'DX4 ', 'DX1 DX4 DX5 ', 'DX3 DX4 ', 'DX3 DX5 ',
       'DX2 DX4 ', 'DX1 DX5 ', 'DX1 DX3 DX4 ', 'DX2 DX3 DX4 ',
       'DX1 DX2 DX3 ', 'DX1 DX3 DX4 DX5 ', 'DX1 DX3 DX5 ',
       'DX1 DX2 DX3 DX5 ', 'DX2 DX3 DX5 ', 'DX2 DX3 DX4 DX5 ',
       'DX1 DX2 DX5 ', 'DX1 DX2 DX4 DX5 ', 'DX2 DX4 DX5 ',
       'DX1 DX2 DX3 DX4 DX5 ', 'DX1 DX2 DX3 DX4 '], dtype=object)

In [ ]:
new = df["Treated_with_drugs"].str.split(" ", n = 5, expand = True) 
df["Treated_with_drugs_1"]= new[0] 
df["Treated_with_drugs_2"]= new[1] 
df["Treated_with_drugs_3"]= new[2] 
df["Treated_with_drugs_4"]= new[3] 
df["Treated_with_drugs_5"]= new[4]

In [ ]:
new1 = test_data["Treated_with_drugs"].str.split(" ", n = 5, expand = True) 
test_data["Treated_with_drugs_1"]= new1[0] 
test_data["Treated_with_drugs_2"]= new1[1] 
test_data["Treated_with_drugs_3"]= new1[2] 
test_data["Treated_with_drugs_4"]= new1[3] 
test_data["Treated_with_drugs_5"]= new1[4]

In [ ]:
#df.drop(columns='Treated_with_drugs',inplace=True)
#test_data.drop(columns='Treated_with_drugs',inplace=True)

In [ ]:
#test_data.drop(columns='Treated_with_drugs',inplace=True)

In [ ]:
import numpy as np
df = df.replace('\\N', np.nan)
df = df.replace('', np.nan)
df = df.replace(" ", np.nan)
df = df.replace('NULL', np.nan)
df = df.replace('null', np.nan)

test_data = test_data.replace('\\N', np.nan)
test_data = test_data.replace('', np.nan)
test_data = test_data.replace(" ", np.nan)
test_data = test_data.replace('NULL', np.nan)
test_data = test_data.replace('null', np.nan)

In [ ]:
df

       ID_Patient_Care_Situation  ...  Patient_mental_condition_Enco
0                          22374  ...                              0
1                          18164  ...                              0
2                           6283  ...                              0
3                           5339  ...                              0
5                          10808  ...                              0
...                          ...  ...                            ...
23092                      15613  ...                              0
23093                      15503  ...                              0
23094                       2167  ...                              0
23095                      31646  ...                              0
23096                       3947  ...                              0

[21849 rows x 31 columns]

In [ ]:
df['Treated_with_drugs_1'].replace(np.nan, "-1",inplace=True)
df['Treated_with_drugs_2'].replace(np.nan, "-1",inplace=True)
df['Treated_with_drugs_3'].replace(np.nan, "-1",inplace=True)
df['Treated_with_drugs_4'].replace(np.nan, "-1",inplace=True)
df['Treated_with_drugs_5'].replace(np.nan, "-1",inplace=True)

In [ ]:
test_data['Treated_with_drugs_1'].replace(np.nan, "-1",inplace=True)
test_data['Treated_with_drugs_2'].replace(np.nan, "-1",inplace=True)
test_data['Treated_with_drugs_3'].replace(np.nan, "-1",inplace=True)
test_data['Treated_with_drugs_4'].replace(np.nan, "-1",inplace=True)
test_data['Treated_with_drugs_5'].replace(np.nan, "-1",inplace=True)

In [ ]:
df.isnull().sum(),test_data.isnull().sum()

(ID_Patient_Care_Situation        0
 Diagnosed_Condition              0
 Patient_ID                       0
 Treated_with_drugs               0
 Patient_Age                      0
 Patient_Body_Mass_Index          0
 Patient_Smoker                   0
 Patient_Rural_Urban              0
 Patient_mental_condition         0
 A                                0
 B                                0
 C                                0
 D                                0
 E                                0
 F                                0
 Z                                0
 Number_of_prev_cond              0
 Survived_1_year                  0
 Treated_with_drugs_1             0
 Treated_with_drugs_2             0
 Treated_with_drugs_3             0
 Treated_with_drugs_4             0
 Treated_with_drugs_5             0
 Treated_with_drugs_1_Enco        0
 Treated_with_drugs_2_Enco        0
 Treated_with_drugs_3_Enco        0
 Treated_with_drugs_4_Enco        0
 Treated_with_drugs_5_Enco        0
 Patient_Smoker_Enco              0
 Patient_Rural_Urban_Enco         0
 Patient_mental_condition_Enco    0
 dtype: int64, ID_Patient_Care_Situation        0
 Diagnosed_Condition              0
 Patient_ID                       0
 Treated_with_drugs               0
 Patient_Age                      0
 Patient_Body_Mass_Index          0
 Patient_Smoker                   0
 Patient_Rural_Urban              0
 Patient_mental_condition         0
 A                                0
 B                                0
 C                                0
 D                                0
 E                                0
 F                                0
 Z                                0
 Number_of_prev_cond              0
 Treated_with_drugs_1             0
 Treated_with_drugs_2             0
 Treated_with_drugs_3             0
 Treated_with_drugs_4             0
 Treated_with_drugs_5             0
 Treated_with_drugs_1_Enco        0
 Treated_with_drugs_2_Enco        0
 Treated_with_drugs_3_Enco        0
 Treated_with_drugs_4_Enco        0
 Treated_with_drugs_5_Enco        0
 Patient_Smoker_Enco              0
 Patient_Rural_Urban_Enco         0
 Patient_mental_condition_Enco    0
 dtype: int64)

In [ ]:
#df.drop(columns='Treated_with_drugs_Enco',inplace=True)

In [ ]:
#test_data.drop(columns='Treated_with_drugs_Enco',inplace=True)

In [ ]:
df.shape,test_data.shape

((21849, 31), (9303, 30))

In [ ]:
df.Treated_with_drugs_1.unique()

array(['DX6', 'DX2', 'DX1', 'DX3', 'DX5', 'DX4'], dtype=object)

In [ ]:
df['Treated_with_drugs_1'].replace("-1", "0",inplace=True)
df['Treated_with_drugs_2'].replace("-1", "0",inplace=True)
df['Treated_with_drugs_3'].replace("-1", "0",inplace=True)
df['Treated_with_drugs_4'].replace("-1", "0",inplace=True)
df['Treated_with_drugs_5'].replace("-1", "0",inplace=True)

df['Treated_with_drugs_1_Enco'] = df['Treated_with_drugs_1'].str[-1:]
df['Treated_with_drugs_2_Enco'] = df['Treated_with_drugs_2'].str[-1:]
df['Treated_with_drugs_3_Enco'] = df['Treated_with_drugs_3'].str[-1:]
df['Treated_with_drugs_4_Enco'] = df['Treated_with_drugs_4'].str[-1:]
df['Treated_with_drugs_5_Enco'] = df['Treated_with_drugs_5'].str[-1:]

In [ ]:
test_data['Treated_with_drugs_1'].replace("-1", "0",inplace=True)
test_data['Treated_with_drugs_2'].replace("-1", "0",inplace=True)
test_data['Treated_with_drugs_3'].replace("-1", "0",inplace=True)
test_data['Treated_with_drugs_4'].replace("-1", "0",inplace=True)
test_data['Treated_with_drugs_5'].replace("-1", "0",inplace=True)

test_data['Treated_with_drugs_1_Enco'] = test_data['Treated_with_drugs_1'].str[-1:]
test_data['Treated_with_drugs_2_Enco'] = test_data['Treated_with_drugs_2'].str[-1:]
test_data['Treated_with_drugs_3_Enco'] = test_data['Treated_with_drugs_3'].str[-1:]
test_data['Treated_with_drugs_4_Enco'] = test_data['Treated_with_drugs_4'].str[-1:]
test_data['Treated_with_drugs_5_Enco'] = test_data['Treated_with_drugs_5'].str[-1:]

In [ ]:
df['Patient_Smoker_Enco']=LabelEncoder().fit_transform(df.Patient_Smoker)
test_data['Patient_Smoker_Enco']=LabelEncoder().fit_transform(test_data.Patient_Smoker)

In [ ]:
df['Patient_Rural_Urban_Enco']=LabelEncoder().fit_transform(df.Patient_Rural_Urban)
test_data['Patient_Rural_Urban_Enco']=LabelEncoder().fit_transform(test_data.Patient_Rural_Urban)

In [ ]:
df['Patient_mental_condition_Enco']=LabelEncoder().fit_transform(df.Patient_mental_condition)
test_data['Patient_mental_condition_Enco']=LabelEncoder().fit_transform(test_data.Patient_mental_condition)

In [ ]:
test_data

      ID_Patient_Care_Situation  ...  Patient_mental_condition_Enco
0                         19150  ...                              0
1                         23216  ...                              0
2                         11890  ...                              0
3                          7149  ...                              0
4                         22845  ...                              0
...                         ...  ...                            ...
9298                      18245  ...                              0
9299                      15598  ...                              0
9300                      11885  ...                              0
9301                      25101  ...                              0
9302                      18855  ...                              0

[9303 rows x 30 columns]

In [ ]:
df.columns

Index(['ID_Patient_Care_Situation', 'Diagnosed_Condition', 'Patient_ID',
       'Treated_with_drugs', 'Patient_Age', 'Patient_Body_Mass_Index',
       'Patient_Smoker', 'Patient_Rural_Urban', 'Patient_mental_condition',
       'A', 'B', 'C', 'D', 'E', 'F', 'Z', 'Number_of_prev_cond',
       'Survived_1_year', 'Treated_with_drugs_1', 'Treated_with_drugs_2',
       'Treated_with_drugs_3', 'Treated_with_drugs_4', 'Treated_with_drugs_5',
       'Treated_with_drugs_1_Enco', 'Treated_with_drugs_2_Enco',
       'Treated_with_drugs_3_Enco', 'Treated_with_drugs_4_Enco',
       'Treated_with_drugs_5_Enco', 'Patient_Smoker_Enco',
       'Patient_Rural_Urban_Enco', 'Patient_mental_condition_Enco'],
      dtype='object')

In [ ]:
df.dtypes

ID_Patient_Care_Situation          int64
Diagnosed_Condition                int64
Patient_ID                         int64
Treated_with_drugs                object
Patient_Age                        int64
Patient_Body_Mass_Index          float64
Patient_Smoker                    object
Patient_Rural_Urban               object
Patient_mental_condition          object
A                                float64
B                                float64
C                                float64
D                                float64
E                                float64
F                                float64
Z                                float64
Number_of_prev_cond              float64
Survived_1_year                    int64
Treated_with_drugs_1              object
Treated_with_drugs_2              object
Treated_with_drugs_3              object
Treated_with_drugs_4              object
Treated_with_drugs_5              object
Treated_with_drugs_1_Enco         object
Treated_with_drugs_2_Enco         object
Treated_with_drugs_3_Enco         object
Treated_with_drugs_4_Enco         object
Treated_with_drugs_5_Enco         object
Patient_Smoker_Enco                int64
Patient_Rural_Urban_Enco           int64
Patient_mental_condition_Enco      int64
dtype: object

In [ ]:
df["Treated_with_drugs_1_Enco"] = df["Treated_with_drugs_1_Enco"].astype(str).astype(int)
df["Treated_with_drugs_2_Enco"] = df["Treated_with_drugs_2_Enco"].astype(str).astype(int)
df["Treated_with_drugs_3_Enco"] = df["Treated_with_drugs_3_Enco"].astype(str).astype(int)
df["Treated_with_drugs_4_Enco"] = df["Treated_with_drugs_4_Enco"].astype(str).astype(int)
df["Treated_with_drugs_5_Enco"] = df["Treated_with_drugs_5_Enco"].astype(str).astype(int)

test_data["Treated_with_drugs_1_Enco"] = test_data["Treated_with_drugs_1_Enco"].astype(str).astype(int)
test_data["Treated_with_drugs_2_Enco"] = test_data["Treated_with_drugs_2_Enco"].astype(str).astype(int)
test_data["Treated_with_drugs_3_Enco"] = test_data["Treated_with_drugs_3_Enco"].astype(str).astype(int)
test_data["Treated_with_drugs_4_Enco"] = test_data["Treated_with_drugs_4_Enco"].astype(str).astype(int)
test_data["Treated_with_drugs_5_Enco"] = test_data["Treated_with_drugs_5_Enco"].astype(str).astype(int)

Model building

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
Train,Val = train_test_split(df, test_size=0.33, random_state=42)

In [ ]:
Train.shape,Val.shape,test_data.shape

((14638, 31), (7211, 31), (9303, 30))

In [ ]:
Train.columns

Index(['ID_Patient_Care_Situation', 'Diagnosed_Condition', 'Patient_ID',
       'Treated_with_drugs', 'Patient_Age', 'Patient_Body_Mass_Index',
       'Patient_Smoker', 'Patient_Rural_Urban', 'Patient_mental_condition',
       'A', 'B', 'C', 'D', 'E', 'F', 'Z', 'Number_of_prev_cond',
       'Survived_1_year', 'Treated_with_drugs_1', 'Treated_with_drugs_2',
       'Treated_with_drugs_3', 'Treated_with_drugs_4', 'Treated_with_drugs_5',
       'Treated_with_drugs_1_Enco', 'Treated_with_drugs_2_Enco',
       'Treated_with_drugs_3_Enco', 'Treated_with_drugs_4_Enco',
       'Treated_with_drugs_5_Enco', 'Patient_Smoker_Enco',
       'Patient_Rural_Urban_Enco', 'Patient_mental_condition_Enco'],
      dtype='object')

In [ ]:
df.head()

   ID_Patient_Care_Situation  ...  Patient_mental_condition_Enco
0                      22374  ...                              0
1                      18164  ...                              0
2                       6283  ...                              0
3                       5339  ...                              0
5                      10808  ...                              0

[5 rows x 31 columns]

In [ ]:
features=['Diagnosed_Condition', 'Patient_Age', 'Patient_Body_Mass_Index',
       'A', 'C', 'E','Number_of_prev_cond', 'Patient_Smoker_Enco',
       'Patient_Rural_Urban_Enco','Treated_with_drugs_1_Enco','Treated_with_drugs_2_Enco']
X_train=Train[features]

In [ ]:
# from sklearn.feature_selection import chi2
# from sklearn.feature_selection import SelectKBest

# # change this to how much features you want to keep from the top ones.
# select_k = 21

# # apply the chi2 score on the data and target (target should be binary).  
# selection = SelectKBest(chi2, k=select_k).fit(X_train, Y_train)

# # display the k selected features.
# features = X_train.columns[selection.get_support()]
# print(features)

In [ ]:
# # import the required functions and object.
# from sklearn.feature_selection import f_classif
# from sklearn.feature_selection import SelectKBest

# # select the number of features you want to retain.
# select_k = 21

# # create the SelectKBest with the mutual info strategy.
# selection = SelectKBest(f_classif, k=select_k).fit(X_train, Y_train)

# # display the retained features.
# features = X_train.columns[selection.get_support()]
# print(features)

In [ ]:
Y_train=Train['Survived_1_year']

In [ ]:
X_Val = Val[features]
Y_Val = Val['Survived_1_year']

In [ ]:
X_test=test_data[features]

In [ ]:
X_train.shape,Y_train.shape,X_Val.shape,Y_Val.shape

((14638, 11), (14638,), (7211, 11), (7211,))

In [ ]:
#With XGB Classifier
from xgboost.sklearn import XGBClassifier
from sklearn.model_selection import RandomizedSearchCV, GridSearchCV
n_estimators = [int(x) for x in np.linspace(start = 100, stop = 400, num = 100)]
    
max_features = ['None','auto','sqrt','log2']
    
max_depth = [int(x) for x in np.linspace(1,50,10)]

learning_rate=[float(x) for x in np.linspace(0.0001,0.01,100)]

random_state=[int(x) for x in np.linspace(start = 0, stop = 50, num = 10)]
#subsample= uniform(0.6, 0.4)
min_samples_split = [2,5,10,12,24,26,30]
    
min_samples_leaf = [1,2,4,6,8,10,12,14,16]
    
#bootstrap = [True]

#the random grid
random_grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'random_state':random_state, 
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
              #'bootstrap': bootstrap
               'learning_rate':learning_rate
               
              }

rf = XGBClassifier()

# rf_random = RandomizedSearchCV(estimator=rf,param_distributions=random_grid,
#                              scoring="accuracy",n_iter=10,
#                               cv = 5, verbose=1, n_jobs=-1,
#                               return_train_score=True)   
rf_random = GridSearchCV(estimator=rf, param_grid=random_grid, scoring='roc_auc', n_jobs=4, cv=5, verbose=3)
best_model = rf_random.fit(X_train,Y_train)
print(best_model.best_params_)

y_pred=rf_random.predict(X_train)
print("Accuracy:",metrics.accuracy_score(Y_train, y_pred))
# testing_data_path = r'C:\Users\KIIT_Intern\Documents\CAA\account_70585\train_test_splitted\test_30.csv'
# make_predictions(testing_data_path,best_model)
# score_indicator(rf,5)

In [ ]:
from mlxtend.feature_selection import SequentialFeatureSelector as sfs

#clf = RandomForestClassifier(n_estimators=100, n_jobs=-1)
clf=XGBClassifier(random_state= 16, n_estimators= 296, min_samples_split= 12, min_samples_leaf= 6, max_features= 'auto', max_depth= 11, learning_rate= 0.0079)

# Build step forward feature selection
sfs1 = sfs(clf,
           k_features=21,
           forward=True,
           floating=False,
           verbose=2,
           scoring='accuracy',
           cv=5)

# Perform SFFS
sfs1 = sfs1.fit(X_train, Y_train)

In [ ]:
import pandas as pd
feature_imp=pd.Series(clf.feature_importances_,index=X_train.columns).sort_values(ascending=False)
print(feature_imp)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from lightgbm import LGBMClassifier
#Create a Gaussian Classifier
#clf=RandomForestClassifier(n_estimators=100,random_state=4)
#Train the model using the training sets y_pred=clf.predict(X_test)

clf=LGBMClassifier(boosting_type='gbdt', num_leaves=31, max_depth=- 1, learning_rate=0.1, n_estimators=100, subsample_for_bin=200000, objective=None, class_weight=None, min_split_gain=0.0, min_child_weight=0.001, min_child_samples=20, subsample=1.0, subsample_freq=0, colsample_bytree=1.0, reg_alpha=0.0, reg_lambda=0.0, random_state=None, n_jobs=- 1, silent=True, importance_type='split')

#clf=XGBClassifier(random_state= 16, n_estimators= 348, min_samples_split= 2, min_samples_leaf= 2, max_features= 'None', max_depth= 6, learning_rate= 0.0077)

clf.fit(X_train,Y_train)

y_pred=clf.predict(X_train)

In [ ]:
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(Y_train, y_pred))

Accuracy: 0.8665118185544474

In [ ]:
y_pred1=clf.predict(X_Val)
print("Accuracy:",metrics.accuracy_score(Y_Val, y_pred1))

Accuracy: 0.8197198724171405

In [ ]:
X_test.drop(columns="Survived_1_year",inplace=True)

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4174: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [ ]:
d=(clf.predict(X_test))

In [ ]:
X_test["Survived_1_year"]=d

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [ ]:
X_test

      Diagnosed_Condition  ...  Survived_1_year
0                      40  ...                1
1                      52  ...                1
2                      50  ...                1
3                      32  ...                0
4                      20  ...                1
...                   ...  ...              ...
9298                   11  ...                0
9299                    7  ...                1
9300                   16  ...                1
9301                   50  ...                0
9302                   51  ...                0

[9303 rows x 12 columns]

In [ ]:
from pandas import DataFrame
Li_sub=list(d)
submit = DataFrame (Li_sub,columns=['prediction'])

In [ ]:
submit.set_index('prediction',inplace=True)
submit

In [ ]:
from google.colab import drive
drive.mount('drive')

Drive already mounted at drive; to attempt to forcibly remount, call drive.mount("drive", force_remount=True).

In [ ]:
submit.to_csv('Hackathon_3_6.csv')

In [ ]:
!cp Hackathon_3_6.csv "drive/My Drive/Hackathon/"

In [ ]:
from sklearn.model_selection import RandomizedSearchCV
# Number of trees in random forest
n_estimators = [int(x) for x in np.linspace(start = 200, stop = 2000, num = 10)]
# Number of features to consider at every split
max_features = ['auto', 'sqrt']
# Maximum number of levels in tree
max_depth = [int(x) for x in np.linspace(10, 110, num = 11)]
max_depth.append(None)
# Minimum number of samples required to split a node
min_samples_split = [2, 5, 10]
# Minimum number of samples required at each leaf node
min_samples_leaf = [1, 2, 4]
# Method of selecting samples for training each tree
bootstrap = [True, False]
# Create the random grid
random_grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
               'bootstrap': bootstrap}

In [ ]:
# Use the random grid to search for best hyperparameters
# First create the base model to tune
rf = RandomForestClassifier()
# Random search of parameters, using 3 fold cross validation, 
# search across 100 different combinations, and use all available cores
rf_random = RandomizedSearchCV(estimator = rf, param_distributions = random_grid, n_iter = 10, cv = 3, verbose=2, random_state=42, n_jobs = -1)
# Fit the random search model
rf_random.fit(X_train, Y_train)

In [ ]:
from sklearn.model_selection import RandomizedSearchCV,GridSearchCV
import lightgbm as lgb
learning_rate= [float(x) for x in np.linspace(0.0001,0.01,100)]
rs_params = {

        'bagging_fraction': (0.5, 0.8),
        'bagging_frequency': (5, 8),
        'learning_rate' : learning_rate,
        'feature_fraction': (0.5, 0.8),
        'max_depth': (10, 13),
        'min_data_in_leaf': (90, 120),
        'num_leaves': (1200, 1550)

}

# Initialize a RandomizedSearchCV object using 5-fold CV-
#rs_cv = RandomizedSearchCV(estimator=lgb.LGBMClassifier(), param_distributions=rs_params, cv = 5, n_iter=100,verbose=1)
rs_cv = GridSearchCV(estimator=lgb.LGBMClassifier(), param_grid=rs_params, scoring='roc_auc', cv=5, verbose=1)
# Train on training data-
rs_cv.fit(X_train, Y_train,verbose=1)
y_pred2=rs_cv.predict(X_Val)
print(rs_cv.best_params_)
print("Accuracy:",metrics.accuracy_score(Y_Val, y_pred2))

Fitting 5 folds for each of 6400 candidates, totalling 32000 fits

[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done  24 tasks      | elapsed:    8.7s
[Parallel(n_jobs=4)]: Done 120 tasks      | elapsed:   33.3s
[Parallel(n_jobs=4)]: Done 280 tasks      | elapsed:  1.2min
[Parallel(n_jobs=4)]: Done 504 tasks      | elapsed:  2.2min
[Parallel(n_jobs=4)]: Done 792 tasks      | elapsed:  3.4min
[Parallel(n_jobs=4)]: Done 1144 tasks      | elapsed:  4.9min
[Parallel(n_jobs=4)]: Done 1560 tasks      | elapsed:  6.7min
[Parallel(n_jobs=4)]: Done 2040 tasks      | elapsed:  8.7min
[Parallel(n_jobs=4)]: Done 2584 tasks      | elapsed: 11.0min
[Parallel(n_jobs=4)]: Done 3192 tasks      | elapsed: 13.6min
[Parallel(n_jobs=4)]: Done 3864 tasks      | elapsed: 16.5min
[Parallel(n_jobs=4)]: Done 4600 tasks      | elapsed: 20.0min
[Parallel(n_jobs=4)]: Done 5400 tasks      | elapsed: 24.0min
[Parallel(n_jobs=4)]: Done 6264 tasks      | elapsed: 28.3min
[Parallel(n_jobs=4)]: Done 7192 tasks      | elapsed: 32.9min
[Parallel(n_jobs=4)]: Done 8184 tasks      | elapsed: 37.7min
[Parallel(n_jobs=4)]: Done 9240 tasks      | elapsed: 42.2min
[Parallel(n_jobs=4)]: Done 10360 tasks      | elapsed: 47.0min
[Parallel(n_jobs=4)]: Done 11544 tasks      | elapsed: 52.0min
[Parallel(n_jobs=4)]: Done 12792 tasks      | elapsed: 57.8min
[Parallel(n_jobs=4)]: Done 14104 tasks      | elapsed: 64.4min